services:
  server:
    build:
      context: .
    ports:
      - 5284:5284
    environment:
      - ASPNETCORE_URLS=http://+:5284
    depends_on:
      - db
      
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: multi-tenant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    expose:
      - 5432
volumes:
  db-data:

